SET FTCM_DIR=Z:\GIT\FTCONTROLSMANAGER
SET FTCMCONFIGURATORE_DIR=Z:\GIT\CONFIGURATOREFTCONTROLSMANAGER
SET VB6PROG="C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE"
SET OUTDIR=D:\FTCONTROLSMANAGER\

SET FTCM_FILENAME=%OUTDIR%\FTCONTROLSMANAGER.EXE
SET FTCMCONFIGURATORE_FILENAME=%OUTDIR%\FTCONTROLSMANAGERCONFIGURATOR.EXE

SET OUT_ERRORLOG_FTCM="Z:\GIT\FT10-Setup-Sourcetree\batch\VB6MAKE_ERRORLOG_FTCONTROLSMANAGER.TXT"
SET OUT_ERRORLOG_FTCMCONFIGURATORE="Z:\GIT\FT10-Setup-Sourcetree\batch\VB6MAKE_ERRORLOG_CONFIGURATOREFTCONTROLSMANAGER.TXT"

SET STAMPVER_DIR=Z:\GIT\FT10-Setup-Sourcetree\batch\STAMPVER.EXE

%VB6PROG% /make "%FTCM_DIR%\FTControlsManager.vbp" /out %OUT_ERRORLOG_FTCM% /outdir %OUTDIR% 

"%STAMPVER_DIR%" -f"10.4.0.0" %FTCM_FILENAME%

%VB6PROG% /make "%FTCMCONFIGURATORE_DIR%\FTControlsManagerConfigurator.vbp" /out %OUT_ERRORLOG_FTCMCONFIGURATORE% /outdir %OUTDIR% 

"%STAMPVER_DIR%" -f"10.4.0.0" %FTCMCONFIGURATORE_FILENAME%