REM ---------------------------------------RFID----------------------------------- 

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE RFID
DEL /F /Q "%RFID_DESTINATION_FOLDER%\*.*"

REM COPIA LE DLL E TLB PER RFID
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.DLL" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.VB6.DLL" %RFID_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.COMMUNICATION.RFID.VB6.TLB" %RFID_DESTINATION_FOLDER%

REM ---------------------------------------DLL DI TDK----------------------------------- 

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE THE DARK KNIGHT
DEL /F /Q "%TDK_DESTINATION_FOLDER%\*.*"

REM COPIA TUTTE LE ALTRE DLL E TLB
COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Cameras.Data.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Checksum.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Exceptions.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.IoC.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Log.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Styles.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.BarcodeScanner.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Channels.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.Modbus.Test.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.C1911.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.dll" %TDK_DESTINATION_FOLDER%

REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v1_00SP.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v1_01SP.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v1_02SP.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v1_03SP.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v1_26QCS.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_00.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_01.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_02.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_03.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_04.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_05.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_06.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_07.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_08.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_09.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_10.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_11.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_12.dll" %TDK_DESTINATION_FOLDER%
REM COPY "%FTCM_SYS_FOLDER%\FT.CM.Plc.U1021.v4_13.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Data.dll" %TDK_DESTINATION_FOLDER%

rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.VB6.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Data.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Business.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Data.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Persistence.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%
rem COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.XlsxReport.Data.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.SystemConfiguration.Persistence.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.VB6Bridge.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Business.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Data.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Persistence.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.dll" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.VB6.dll" %TDK_DESTINATION_FOLDER%

COPY "%FTCM_SYS_FOLDER%\FT.CM.AlarmsAndEvents.Presentation.VB6.tlb " %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Common.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Communication.BarcodeScanner.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Controls.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Diagnostics.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Historics.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Products.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.EdibleOil.Business.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Reporting.Princess.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Security.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.VB6Bridge.tlb" %TDK_DESTINATION_FOLDER%
COPY "%FTCM_SYS_FOLDER%\FT.CM.Maintenance.Presentation.VB6.tlb" %TDK_DESTINATION_FOLDER%


REM -----------------------------------EXE FTCONTROLSMANAGER E FTCONROLSMANAGERCONFIGURATORE----------------------------------- 

REM RIPULISCE LA DIRECTORY DI DESTINAZIONE ESEGUIBILI FTCONTROLSMANAGER
DEL /F /Q "%FTCM_EXE_DESTINATION_FOLDER%\*.*"

COPY "%FTCM_EXE_SOURCE_FOLDER%\FTCONTROLSMANAGER.EXE" %FTCM_EXE_DESTINATION_FOLDER%
COPY "%FTCM_EXE_SOURCE_FOLDER%\FTCONTROLSMANAGERCONFIGURATOR.EXE" %FTCM_EXE_DESTINATION_FOLDER%
COPY "%FTCM_TEMPLATE_INI_FOLDER%\FTControlsManager.ini" "%FTCM_EXE_DESTINATION_FOLDER%\FTCONTROLSMANAGER.INI.%FTCM_VERSIONE%"
pause